import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(new URL('../server/package.json', import.meta.url));
const db = require('./db');
const origin = process.env.APP_ORIGIN;
const page = await fetch(origin + '/jobs').then(r => r.text());
assert.match(page, /founding engineer/);
assert.match(page, /founding growth/);
assert.match(page, /id="application"/);
assert.doesNotMatch(page, /jobs@applyapply/);
assert.equal((await fetch(origin + '/admin/job-applications')).status, 403);
const submit = body => fetch(origin + '/jobs/apply', {method: 'POST', headers: {'content-type':'application/json'}, body: JSON.stringify(body)});
const valid = {role:'engineer',name:'Test Candidate',email:'candidate@example.com',link:'https://example.com/work',note:'I have built a browser extension and a job board.'};
assert.equal((await submit({...valid,link:'javascript:alert(1)'})).status,400);
assert.equal((await submit({...valid,role:'other'})).status,400);
assert.equal((await submit(valid)).status,200);
const rows = await db.pool.query("SELECT * FROM feedback WHERE kind='job_application'");
assert.equal(rows.rows.length,1);
assert.equal(rows.rows[0].user_email,valid.email);
assert.equal(rows.rows[0].context.role,'engineer');
assert.equal(rows.rows[0].message,valid.note);
assert.equal((await submit({...valid,website:'spam'})).status,200);
assert.equal((await db.pool.query("SELECT count(*) FROM feedback WHERE kind='job_application'")).rows[0].count,'1');
await db.pool.end();
console.log('PASS: hiring page, validation, persistence, honeypot, and private application access');
